#!/usr/bin/env bash


if [[ $1 -eq "i" ]]; then

	rsync -avz --progress freya:~/track.areteh.co/db/tracks.db ./

else

	scp arew:/home/freyabison/track.areteh.co/db/tracks.db ./

fi

rm -r ./out* test/

go run dump.go

cp out.mbtiles ./TileServer/tiles.mbtiles
#easy_install mbutil
#mb-util out.mbtiles test --image_format=png


#http://gis.stackexchange.com/questions/3712/create-vector-tiles-for-polymaps
#http://gis.stackexchange.com/questions/65735/geojson-in-leaflet


#https://github.com/klokantech/vector-tiles-sample


#mb-util --image_format=png out.mbtiles test/web

#tippecanoe-decode out.mbtiles |more
